-- Supabase Schema for Mitishirube App (MVP + Future Extensible)

-- 1. Events Table
-- Stores the main event details.
CREATE TABLE IF NOT EXISTS public.events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT NOT NULL UNIQUE, -- e.g., 'michishirube-2026'
    name TEXT NOT NULL,
    subtitle TEXT,
    date TEXT,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Booths Table
-- Stores information about each booth.
CREATE TABLE IF NOT EXISTS public.booths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    
    -- MVP Fields (Filters & Map)
    theme TEXT CHECK (theme IN ('Parenting', 'Society', 'Kids', 'Other')),
    type TEXT CHECK (type IN ('Seminar', 'Experience', 'Show', 'Other')),
    map_x FLOAT, -- X coordinate % (0-100)
    map_y FLOAT, -- Y coordinate % (0-100)
    location_name TEXT, -- Display name for location (e.g. "Room A")

    -- Future / Interactive Fields
    congestion_status TEXT DEFAULT 'unknown' CHECK (congestion_status IN ('unknown', 'empty', 'crowded', 'full')),
    reservation_url TEXT, -- External URL or internal ID
    reservation_status TEXT DEFAULT 'available', -- Simple status text
    is_chat_active BOOLEAN DEFAULT false,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Schedule Table
-- Timetable for event programs.
CREATE TABLE IF NOT EXISTS public.schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    booth_id BIGINT REFERENCES public.booths(id) ON DELETE SET NULL, -- Optional link to a booth
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Booth Posts (News) Table
-- Updates posted by booth owners.
CREATE TABLE IF NOT EXISTS public.booth_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    booth_id BIGINT REFERENCES public.booths(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    posted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. User Profiles (Auth)
-- Extends Supabase Auth. Links users to specific booths.
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    role TEXT DEFAULT 'staff' CHECK (role IN ('admin', 'staff', 'booth_owner')),
    booth_id BIGINT REFERENCES public.booths(id) ON DELETE SET NULL, -- If null, regular staff (or admin)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booths ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booth_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Public Read Access (Everyone can view)
CREATE POLICY "Public events are viewable by everyone" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public booths are viewable by everyone" ON public.booths FOR SELECT USING (true);
CREATE POLICY "Public schedule is viewable by everyone" ON public.schedule FOR SELECT USING (true);
CREATE POLICY "Public posts are viewable by everyone" ON public.booth_posts FOR SELECT USING (true);

-- Admin/Staff Write Access (Mocking a simple rule for MVP: Authenticated users can INSERT/UPDATE)
-- In a real production app, you would check user_profiles.role here.
CREATE POLICY "Authenticated users can insert posts" ON public.booth_posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update their booth" ON public.booths FOR UPDATE USING (auth.role() = 'authenticated');

-- Seed Data (Sample)
-- Insert Event
INSERT INTO public.events (slug, name, subtitle, date, location)
VALUES ('michishirube-2026', 'Michishirube 2026', '集い、響き合い、一歩踏み出す。', '2026-02-14', '沖縄国際大学');

-- Insert Booths (assuming event ID is the one just created - tricky in pure SQL script without variables, easiest to run manually or assume single event context)
-- NOTE: Update the UUID below after creating the event if running step-by-step.
-- For this script, we rely on the first event or manual entry.
