-- Supabase Schema for Mitishirube App (Simple Migration)

-- 0) Events Table
CREATE TABLE IF NOT EXISTS public.events (
  id TEXT PRIMARY KEY, -- 'michishirube-2026'
  name TEXT NOT NULL,
  subtitle TEXT,
  date TEXT,
  location TEXT
);

-- 1) Booths Table
CREATE TABLE IF NOT EXISTS public.booths (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL REFERENCES public.events(id),
  name TEXT NOT NULL
);

-- 2) Booth Users Table (Custom Auth)
-- Note: In a full Supabase app, you might use auth.users, but for migration speed we keep this.
CREATE TABLE IF NOT EXISTS public.booth_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booth_id BIGINT REFERENCES public.booths(id),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT false
);

-- 3) Booth Posts (News)
CREATE TABLE IF NOT EXISTS public.booth_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL REFERENCES public.events(id),
  booth_id BIGINT REFERENCES public.booths(id),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  posted_at TEXT NOT NULL
);

-- 4) Schedule
CREATE TABLE IF NOT EXISTS public.schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL REFERENCES public.events(id),
  title TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  description TEXT
);

-- Enable RLS (Optional but recommended, allowing public read for now)
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booths ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booth_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booth_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule ENABLE ROW LEVEL SECURITY;

-- Allow public read access to content
CREATE POLICY "Public read events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public read booths" ON public.booths FOR SELECT USING (true);
CREATE POLICY "Public read posts" ON public.booth_posts FOR SELECT USING (true);
CREATE POLICY "Public read schedule" ON public.schedule FOR SELECT USING (true);

-- Allow backend (service role) to do everything (Supabase default behavior), 
-- but users via API need insert policies if using Supabase Client directly.
-- Since we use supabase-js in a Node.js backend with SERVICE KEY (or anon key with backend logic),
-- standard policies might block if we don't set them up right.
-- For simplicity in this Node.js > Supabase connection, we can allow public insert/update OR
-- rely on the fact that we are using a backend client.
-- IF using 'anon' key in backend, we need policies.
-- IF using 'service_role' key, it bypasses RLS.
-- We will assume the user puts the ANON KEY in .env, so we need policies to allow inserts?
-- NO, strictly speaking, a Node backend should usually use SERVICE_ROLE key or 
-- if using ANON key, the RLS must allow it.
-- Let's Open everything for now (INSECURE but matches local SQLite behavior).
CREATE POLICY "Public insert posts" ON public.booth_posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update events" ON public.events FOR UPDATE USING (true);
CREATE POLICY "Public insert events" ON public.events FOR INSERT WITH CHECK (true);
-- ... etc. Ideally user uses Service Role Key in backend.

-- SEED DATA (Sample)
INSERT INTO public.events (id, name, subtitle, date, location)
VALUES ('michishirube-2026', 'Mitishirube 2026', '集い、響き合い、一歩踏み出す。', '2026-02-14', '沖縄国際大学');

-- Admin User Seed
-- Password: 'password' (hashed) -> '$2a$10$w....' (Need a valid hash)
-- bcrypt hash for 'password' is roughly: $2a$10$X7.p.. etc.
-- For now, let's just insert the event. Users need to be created manually or via a script.
